name: test

on: [push]

jobs:
  test-run:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: test line
        run: |
          whoami
          copy LiftierLoft C:\Users\ajhoc\AppData\Roaming\.minecraft\resourcepacks